#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Local Project Mode Switcher
============================
Quick physical switcher embedded inside project.
Self-contained, multi-IDE synchronized, and supports parameter-less status echoing.
<!-- 🛡️ SEEDED_SKILL_VENDORED: Generated by agent_multi_rules_architect. DO NOT EDIT DIRECTLY. -->
"""
import sys
import shutil
from pathlib import Path

PROFILES_DIR_NAME = ".agent_profiles"
CURRENT_MODE_FILE = ".current_mode"

def get_root_dir() -> Path:
    curr = Path(__file__).resolve().parent
    for p in [curr] + list(curr.parents):
        if (p / PROFILES_DIR_NAME).is_dir():
            return p
    return curr.parent

def switch_mode(target_mode: str):
    root = get_root_dir()
    target = target_mode.lower().strip()
    
    if target in ["prod", "production", "office"]:
        mode_key = "production"
    elif target in ["dev", "development", "engineering"]:
        mode_key = "development"
    else:
        mode_key = target
        
    profiles_dir = root / PROFILES_DIR_NAME
    src_dir = profiles_dir / mode_key
    
    if not src_dir.is_dir():
        print(f"❌ 錯誤：找不到模式目錄 `{src_dir}`！")
        sys.exit(1)
        
    # Copy all files (AGENTS.md, CLAUDE.md, .cursorrules, etc.) to root
    for item in src_dir.iterdir():
        if item.is_file():
            shutil.copy2(item, root / item.name)
            
    (profiles_dir / CURRENT_MODE_FILE).write_text(f"{mode_key}\n", encoding="utf-8")
    
    mode_icon = "💼" if mode_key == "production" else "🛠️"
    mode_label = "生產/辦公模式 (Production)" if mode_key == "production" else "研發/開發模式 (Development)"
    print("\n" + "=" * 72)
    print(f"  {mode_icon} 【{root.name}】專案規則已物理切換為：【{mode_label}】")
    print("=" * 72)
    print("  👉 重要提醒：")
    print("     1. 請立即在 IDE 點擊「New Chat (新對話)」以載入純淨的模式上下文！")
    print("     2. 舊對話會殘留先前的上下文記憶，唯有開啟新對話才能 100% 生效。")
    print("=" * 72 + "\n")

def show_status():
    root = get_root_dir()
    profiles_dir = root / PROFILES_DIR_NAME
    mode_file = profiles_dir / CURRENT_MODE_FILE
    
    current_mode = "unknown"
    if mode_file.is_file():
        current_mode = mode_file.read_text(encoding="utf-8").strip()
        
    mode_icon = "💼" if current_mode == "production" else ("🛠️" if current_mode == "development" else "⚙️")
    mode_label = "生產/辦公模式 (Production)" if current_mode == "production" else ("研發/開發模式 (Development)" if current_mode == "development" else current_mode)
    
    print("\n" + "=" * 72)
    print(f"  {mode_icon} 【{root.name}】當前運作模式：【{mode_label}】")
    print("=" * 72)
    print("  🔄 切換指令用法：")
    print("     - 切換至生產模式: py switch_mode.py prod")
    print("     - 切換至開發模式: py switch_mode.py dev")
    print("=" * 72 + "\n")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        show_status()
    else:
        switch_mode(sys.argv[1])
